# Generated by Django 5.2.3 on 2025-06-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_rename_actie_movie_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
